# NumPy Practices

In [1]:
import numpy as np

In [2]:
print("numpy version ",np.__version__)

numpy version  2.3.2


In [3]:
# Scaler (0D Array)
arr0 = np.array(0)
arr0.ndim

0

In [9]:
# Vector (1D Array)
arr1 = np.array([1,2,3,4,5,6])
arr1.ndim

1

In [12]:
arr1_new = arr1.reshape(2,3)
arr1_new.ndim

2

In [5]:
# Matrices (2D Array)
arr2 = np.array([[1,1,2,4,5,6],[3,4,6,67,843,1]])
arr2.shape

(2, 6)

In [14]:
arr2.reshape(4,3)

array([[  1,   1,   2],
       [  4,   5,   6],
       [  3,   4,   6],
       [ 67, 843,   1]])

In [8]:
# 3D Array(Combination of 2D Array)
arr3 = np.array([[[1,2,3,4,5],[5,4,3,2,1]],[[0,9,8,7,6],[6,7,8,9,0]]])
arr3

array([[[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]],

       [[0, 9, 8, 7, 6],
        [6, 7, 8, 9, 0]]])

In [18]:
arr4 = np.array([[[[1,1,1,1,1],[2,2,2,2,2]],[[3,3,3,3,3],[4,4,4,4,4]]],[[[11,11,11,11,11],[22,22,22,22,22]],[[33,33,33,33,33],[44,44,44,44,44]]]])
arr4

array([[[[ 1,  1,  1,  1,  1],
         [ 2,  2,  2,  2,  2]],

        [[ 3,  3,  3,  3,  3],
         [ 4,  4,  4,  4,  4]]],


       [[[11, 11, 11, 11, 11],
         [22, 22, 22, 22, 22]],

        [[33, 33, 33, 33, 33],
         [44, 44, 44, 44, 44]]]])

In [19]:
arr4.ndim

4

#### Tensors = Dimensions of the array

## NumPy Functions

#### arange() and reshape()

In [29]:
# 4D Array((Combination of 3D Array))
arr4 = np.arange(16).reshape(4,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Zeros and Ones and empty

In [35]:
zeros = np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [11]:
ones = np.ones((4,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.empty((2,2))

array([[0.00000000e+000, 9.07558097e-312],
       [9.07558097e-312, 9.07558097e-312]])

#### Arange(start, stop, step)

In [36]:
arr_range = np.arange(0,16,4)
arr_range

array([ 0,  4,  8, 12])

#### sort() and concatenate()

In [14]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,2,6,3])
np.sort(arr2)

array([2, 3, 4, 5, 6])

In [38]:
names = np.array(["vikas","naman","himanshu","Anjali"])
np.sort(names)

array(['Anjali', 'himanshu', 'naman', 'vikas'], dtype='<U8')

In [15]:
con_array = np.concatenate([arr1,arr2])
con_array

array([1, 2, 3, 4, 5, 5, 4, 2, 6, 3])

In [16]:
con_array.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [5, 4, 2, 6, 3]])

In [17]:
con_array.shape

(10,)

#### Arithmetic Operations

In [50]:
arr = np.array([10,20,35,43])
arr2 = np.array([1,2,3,4])
np.add(arr,arr2)

array([11, 22, 38, 47])

In [51]:
np.subtract(arr,arr2)

array([ 9, 18, 32, 39])

In [52]:
np.multiply(arr,arr2)

array([ 10,  40, 105, 172])

In [53]:
np.divide(arr,arr2)

array([10.        , 10.        , 11.66666667, 10.75      ])

In [54]:
np.power(arr,arr2)

array([     10,     400,   42875, 3418801])

In [55]:
np.mod(arr,arr2)

array([0, 0, 2, 3])

#### String functions

In [24]:
str_arr = np.array(["Raj","HImanshu","Raghav"])

In [25]:
np.char.upper(str_arr)

array(['RAJ', 'HIMANSHU', 'RAGHAV'], dtype='<U8')

In [26]:
np.char.lower(str_arr)

array(['raj', 'himanshu', 'raghav'], dtype='<U8')

In [27]:
np.char.add(str_arr," mishra")

array(['Raj mishra', 'HImanshu mishra', 'Raghav mishra'], dtype='<U15')

In [28]:
np.char.replace(str_arr,"Raj","Mohan")

array(['Mohan', 'HImanshu', 'Raghav'], dtype='<U8')

In [29]:
np.char.split("Hello ffrom this side ")

array(list(['Hello', 'ffrom', 'this', 'side']), dtype=object)

In [ ]:
num = list(map(int, input("Enter numbers with space : ").split()))
num

#### Map Function
map(function, iterable)  
function perform on all the items of Iterable(list, tuple, set)

In [ ]:
def square(x):
    return x*x

In [ ]:
lst = np.array([1,2,3,4,5])
result = map(square, lst)

In [ ]:
result_list = list(result)
result_list

### Statistical Function (sum, mean, median, std, var, min, max, argmin, argmax)

In [ ]:
np.sum(result_list)

In [ ]:
np.mean(result_list)

In [ ]:
np.median(result_list)

In [ ]:
np.std(result_list)

In [ ]:
np.var(result_list)

In [ ]:
np.min(result_list)

In [ ]:
np.argmin(result_list)

In [ ]:
np.max(result_list)

In [ ]:
np.argmax(result_list)

### Random Number Generation

In [56]:
# Floading point random number (between 0 and 1)
np.random.rand(3,4)

array([[0.52357337, 0.97128582, 0.15876091, 0.27958647],
       [0.35814954, 0.59758351, 0.86915463, 0.87878815],
       [0.63537565, 0.42919866, 0.78044763, 0.97570681]])

In [60]:
np.random.randint(10)

1

In [ ]:
# Random Integers in range and value
#np.random.rand(start_range, end_range, total_numbers)
np.random.randint(1,10,5)

#### Seed(Reproducibility) - seed() is helpful for getting the same random numbers every time.

In [61]:
np.random.randint(1,20,5)

array([11,  9,  4,  9, 11], dtype=int32)

In [67]:
# With seed
np.random.seed(2)
np.random.randint(1,20,10)

array([ 9, 16, 14,  9, 12, 19, 12,  9,  8,  3], dtype=int32)