<a href="https://colab.research.google.com/github/himanshu2285/ML-practices/blob/main/numpyPractices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

In [ ]:
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a.size

9

In [ ]:
b = a[1:3,]
b

array([[2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.hstack(b)

array([2, 2, 2, 3, 3, 3])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
data = np.array([2,3])
ones = np.ones(2,dtype=int)

In [ ]:
data+ones

array([3, 4])

In [ ]:
x= np.array([
    [1,2,3],[3,2,1]
])
x

array([[1, 2, 3],
       [3, 2, 1]])

In [ ]:
x.ndim

2

In [ ]:
x = np.array([
    [[11,12,12,32],[54,33,45,76],[43,4565,67,334]],
    [[3,4,53,3],[5,3,255,1],[1,2,3,4]]
])
x

array([[[  11,   12,   12,   32],
        [  54,   33,   45,   76],
        [  43, 4565,   67,  334]],

       [[   3,    4,   53,    3],
        [   5,    3,  255,    1],
        [   1,    2,    3,    4]]])

In [ ]:
x.ndim

3

In [ ]:
x.max(axis=0)

array([[  11,   12,   53,   32],
       [  54,   33,  255,   76],
       [  43, 4565,   67,  334]])

In [ ]:
import random
randomNum = np.random.random(3)
randomNum

array([0.72491293, 0.85971201, 0.03563076])

In [ ]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.63867884, 0.96141868, 0.99671938])

### Aggregate Funcation

In [ ]:
array1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

In [ ]:
print(array1.min())
print(array1.max())
print(array1.sum())
print(array1.mean())
print(array1.std())
print(array1.var())
print(array1.cumsum())
print(array1.argmin())
print(array1.argmax())

1
15
120
8.0
4.320493798938574
18.666666666666668
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
0
14


Axis function: axis=1 means row, axis=0 means column

In [ ]:
print(np.sum(array1, axis=0))
print(np.sum(array1, axis=1))

[18 21 24 27 30]
[15 40 65]


### Filtering elements in an array

In [ ]:
ages = np.array([
    [23,54,5,33,21],
    [65,45,20,21,26]
])

In [ ]:
teens = ages[ages<20]
teens

array([5])

In [ ]:
adults = ages[(ages>=20) & (ages<65)]
adults

array([23, 54, 33, 21, 45, 20, 21, 26])

where clause is helpful for preserving our original shape

In [ ]:
newArr = np.where(ages>20, ages, 0)
print(newArr)

[[23 54  0 33 21]
 [65 45  0 21 26]]


## Random Numbers

In [ ]:
rng = np.random.default_rng()
# print(rng.integers(low=1,high=10,size=(3)))
print(rng.integers(low=1,high=11,size=(3,3)))

[[7 8 8]
 [1 7 3]
 [8 8 6]]


Uniform gives all values equal chance

In [ ]:
print(np.random.uniform(-1,1,size=(2,3,3)))

[[[ 0.73096827  0.32947845  0.18096484]
  [ 0.46459037 -0.03018289 -0.80223877]
  [-0.05677044 -0.46699893 -0.16740865]]

 [[ 0.07573953  0.88332801 -0.40794144]
  [ 0.7264531  -0.65877005 -0.39512646]
  [-0.8214704   0.88522239  0.06716791]]]


Shuffling values

In [ ]:
array = np.array([1,2,3,4,5,6])
fruits = np.array(['apple','banana','cherry','orange','grapes'])
rng = np.random.default_rng()
rng.shuffle(fruits)
fruits

array(['orange', 'grapes', 'apple', 'banana', 'cherry'], dtype='<U6')

choice() function is used for selecting the random values

In [ ]:
fruit = rng.choice(fruits,size=(2,3))
fruit

array([['grapes', 'orange', 'apple'],
       ['grapes', 'cherry', 'apple']], dtype='<U6')