<a href="https://colab.research.google.com/github/himanshu2285/ML-practices/blob/main/numpyPractices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

In [3]:
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [4]:
a.ndim

2

In [5]:
a.shape

(3, 3)

In [6]:
a.size

9

In [8]:
b = a[1:3,]
b

array([[2, 2, 2],
       [3, 3, 3]])

In [12]:
np.hstack(b)

array([2, 2, 2, 3, 3, 3])

In [15]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
data = np.array([2,3])
ones = np.ones(2,dtype=int)

In [20]:
data+ones

array([3, 4])

In [21]:
x= np.array([
    [1,2,3],[3,2,1]
])
x

array([[1, 2, 3],
       [3, 2, 1]])

In [22]:
x.ndim

2

In [36]:
x = np.array([
    [[11,12,12,32],[54,33,45,76],[43,4565,67,334]],
    [[3,4,53,3],[5,3,255,1],[1,2,3,4]]
])
x

array([[[  11,   12,   12,   32],
        [  54,   33,   45,   76],
        [  43, 4565,   67,  334]],

       [[   3,    4,   53,    3],
        [   5,    3,  255,    1],
        [   1,    2,    3,    4]]])

In [37]:
x.ndim

3

In [38]:
x.max(axis=0)

array([[  11,   12,   53,   32],
       [  54,   33,  255,   76],
       [  43, 4565,   67,  334]])

In [43]:
import random
randomNum = np.random.random(3)
randomNum

array([0.17862996, 0.58986318, 0.10024777])

In [50]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.39272003, 0.67978353, 0.41738907])